// Generated from emma.css with css2h.py

#ifndef _THEME_EMMA_H_
#define _THEME_EMMA_H_

typedef enum {
    ThemeEmmaColor_Surface_Highest,
    ThemeEmmaColor_Surface_Higher,
    ThemeEmmaColor_Surface_High,
    ThemeEmmaColor_Surface_Base,
    ThemeEmmaColor_Surface_Low,
    ThemeEmmaColor_Surface_Lower,
    ThemeEmmaColor_Surface_Lowest,
    ThemeEmmaColor_Surface_Transparent,
    ThemeEmmaColor_Background_Blanket_Light,
    ThemeEmmaColor_Background_Blanket_Medium,
    ThemeEmmaColor_Background_Blanket_Strong,
    ThemeEmmaColor_Background_System_Base_On_Light,
    ThemeEmmaColor_Background_System_Base_On_Dark,
    ThemeEmmaColor_Background_System_Subtle_On_Light,
    ThemeEmmaColor_Background_System_Subtle_On_Dark,
    ThemeEmmaColor_Text_Subtle_On_Dark,
    ThemeEmmaColor_Text_Subtle_On_Light,
    ThemeEmmaColor_Icon_Subtle_On_Light,
    ThemeEmmaColor_Icon_Subtle_On_Dark,
    ThemeEmmaColor_Border_Subtle_On_Light,
    ThemeEmmaColor_Border_Subtle_On_Dark,
    ThemeEmmaColor_Background_System_Strong_On_Light,
    ThemeEmmaColor_Background_System_Strong_On_Dark,
    ThemeEmmaColor_Background_System_Hovered_On_Light,
    ThemeEmmaColor_Background_System_Hovered_On_Dark,
    ThemeEmmaColor_Background_Brand_Base,
    ThemeEmmaColor_Background_Brand_Subtle,
    ThemeEmmaColor_Background_Brand_Strong,
    ThemeEmmaColor_Background_Brand_Hovered,
    ThemeEmmaColor_Text_Brand_Base,
    ThemeEmmaColor_Text_Brand_Subtle,
    ThemeEmmaColor_Text_Brand_Strong,
    ThemeEmmaColor_Text_Brand_On_Brand,
    ThemeEmmaColor_Icon_Brand_Base,
    ThemeEmmaColor_Icon_Brand_Subtle,
    ThemeEmmaColor_Icon_Brand_Strong,
    ThemeEmmaColor_Icon_Brand_On_Brand,
    ThemeEmmaColor_Border_Brand_Subtle,
    ThemeEmmaColor_Border_Brand_Base,
    ThemeEmmaColor_Border_Brand_Strong,
    ThemeEmmaColor_Background_Secondary_Base,
    ThemeEmmaColor_Background_Secondary_Subtle,
    ThemeEmmaColor_Background_Secondary_Strong,
    ThemeEmmaColor_Background_Secondary_Hovered,
    ThemeEmmaColor_Text_Secondary_Base,
    ThemeEmmaColor_Text_Secondary_Subtle,
    ThemeEmmaColor_Text_Secondary_Strong,
    ThemeEmmaColor_Text_Secondary_On_Secondary,
    ThemeEmmaColor_Icon_Secondary_Base,
    ThemeEmmaColor_Icon_Secondary_Subtle,
    ThemeEmmaColor_Icon_Secondary_Strong,
    ThemeEmmaColor_Icon_Secondary_On_Secondary,
    ThemeEmmaColor_Border_Secondary_Subtle,
    ThemeEmmaColor_Border_Secondary_Base,
    ThemeEmmaColor_Border_Secondary_Strong,
    ThemeEmmaColor_Background_Danger_Base,
    ThemeEmmaColor_Background_Danger_Subtle,
    ThemeEmmaColor_Background_Danger_Strong,
    ThemeEmmaColor_Background_Danger_Hovered,
    ThemeEmmaColor_Text_Danger_Base,
    ThemeEmmaColor_Text_Danger_Subtle,
    ThemeEmmaColor_Text_Danger_Strong,
    ThemeEmmaColor_Text_Danger_On_Danger,
    ThemeEmmaColor_Icon_Danger_Base,
    ThemeEmmaColor_Icon_Danger_Subtle,
    ThemeEmmaColor_Icon_Danger_Strong,
    ThemeEmmaColor_Icon_Danger_On_Danger,
    ThemeEmmaColor_Border_Danger_Subtle,
    ThemeEmmaColor_Border_Danger_Base,
    ThemeEmmaColor_Border_Danger_Strong,
    ThemeEmmaColor_Background_Warning_Base,
    ThemeEmmaColor_Background_Warning_Subtle,
    ThemeEmmaColor_Background_Warning_Strong,
    ThemeEmmaColor_Background_Warning_Hovered,
    ThemeEmmaColor_Text_Warning_Base,
    ThemeEmmaColor_Text_Warning_Subtle,
    ThemeEmmaColor_Text_Warning_Strong,
    ThemeEmmaColor_Text_Warning_On_Warning,
    ThemeEmmaColor_Icon_Warning_Base,
    ThemeEmmaColor_Icon_Warning_Subtle,
    ThemeEmmaColor_Icon_Warning_Strong,
    ThemeEmmaColor_Icon_Warning_On_Warning,
    ThemeEmmaColor_Border_Warning_Subtle,
    ThemeEmmaColor_Border_Warning_Base,
    ThemeEmmaColor_Border_Warning_Strong,
    ThemeEmmaColor_Background_Success_Base,
    ThemeEmmaColor_Background_Success_Subtle,
    ThemeEmmaColor_Background_Success_Strong,
    ThemeEmmaColor_Background_Success_Hovered,
    ThemeEmmaColor_Text_Success_Base,
    ThemeEmmaColor_Text_Success_Subtle,
    ThemeEmmaColor_Text_Success_Strong,
    ThemeEmmaColor_Text_Success_On_Success,
    ThemeEmmaColor_Icon_Success_Base,
    ThemeEmmaColor_Icon_Success_Subtle,
    ThemeEmmaColor_Icon_Success_Strong,
    ThemeEmmaColor_Icon_Success_On_Success,
    ThemeEmmaColor_Border_Success_Subtle,
    ThemeEmmaColor_Border_Success_Base,
    ThemeEmmaColor_Border_Success_Strong,
    ThemeEmmaColor_Background_Information_Base,
    ThemeEmmaColor_Background_Information_Subtle,
    ThemeEmmaColor_Background_Information_Strong,
    ThemeEmmaColor_Background_Information_Hovered,
    ThemeEmmaColor_Text_Information_Base,
    ThemeEmmaColor_Text_Information_Subtle,
    ThemeEmmaColor_Text_Information_Strong,
    ThemeEmmaColor_Text_Information_On_Information,
    ThemeEmmaColor_Icon_Information_Base,
    ThemeEmmaColor_Icon_Information_Subtle,
    ThemeEmmaColor_Icon_Information_Strong,
    ThemeEmmaColor_Icon_Information_On_Information,
    ThemeEmmaColor_Border_Information_Subtle,
    ThemeEmmaColor_Border_Information_Base,
    ThemeEmmaColor_Border_Information_Strong,
    ThemeEmmaColor_Background_Disabled_On_Light,
    ThemeEmmaColor_Background_Disabled_On_Dark,
    ThemeEmmaColor_Text_Disabled_On_Light,
    ThemeEmmaColor_Text_Disabled_On_Dark,
    ThemeEmmaColor_Icon_Disabled_On_Light,
    ThemeEmmaColor_Icon_Disabled_On_Dark,
    ThemeEmmaColor_Border_Disabled_On_Light,
    ThemeEmmaColor_Border_Disabled_On_Dark,
    ThemeEmmaColor_Text_On_Dark,
    ThemeEmmaColor_Text_On_Light,
    ThemeEmmaColor_Text_Interactive,
    ThemeEmmaColor_Text_Subtlest_On_Dark,
    ThemeEmmaColor_Text_Subtlest_On_Light,
    ThemeEmmaColor_Icon_Subtlest_On_Light,
    ThemeEmmaColor_Icon_Subtlest_On_Dark,
    ThemeEmmaColor_Border_Subtlest_On_Light,
    ThemeEmmaColor_Border_Subtlest_On_Dark,
    ThemeEmmaColor_Icon_On_Dark,
    ThemeEmmaColor_Icon_On_Light,
    ThemeEmmaColor_Border_On_Dark,
    ThemeEmmaColor_Border_On_Light,
    ThemeEmmaColor_COUNT,
} ThemeEmmaColor;

static const float THEME_EMMA_COLOR[][4] ={
    [ThemeEmmaColor_Surface_Highest] = { 1.00f, 1.00f, 1.00f, 1.00f },
    [ThemeEmmaColor_Surface_Higher] = { 0.96f, 0.97f, 0.97f, 1.00f },
    [ThemeEmmaColor_Surface_High] = { 0.91f, 0.91f, 0.91f, 1.00f },
    [ThemeEmmaColor_Surface_Base] = { 0.69f, 0.69f, 0.69f, 1.00f },
    [ThemeEmmaColor_Surface_Low] = { 0.28f, 0.29f, 0.30f, 1.00f },
    [ThemeEmmaColor_Surface_Lower] = { 0.17f, 0.19f, 0.21f, 1.00f },
    [ThemeEmmaColor_Surface_Lowest] = { 0.12f, 0.13f, 0.16f, 1.00f },
    [ThemeEmmaColor_Surface_Transparent] = { 1.00f, 1.00f, 1.00f, 0.05f },
    [ThemeEmmaColor_Background_Blanket_Light] = { 0.00f, 0.00f, 0.00f, 0.40f },
    [ThemeEmmaColor_Background_Blanket_Medium] = { 0.00f, 0.00f, 0.00f, 0.60f },
    [ThemeEmmaColor_Background_Blanket_Strong] = { 0.00f, 0.00f, 0.00f, 0.90f },
    [ThemeEmmaColor_Background_System_Base_On_Light] = { 0.96f, 0.97f, 0.97f, 1.00f },
    [ThemeEmmaColor_Background_System_Base_On_Dark] = { 0.17f, 0.19f, 0.21f, 1.00f },
    [ThemeEmmaColor_Background_System_Subtle_On_Light] = { 0.96f, 0.96f, 0.96f, 1.00f },
    [ThemeEmmaColor_Background_System_Subtle_On_Dark] = { 0.12f, 0.13f, 0.16f, 1.00f },
    [ThemeEmmaColor_Text_Subtle_On_Dark] = { 0.69f, 0.69f, 0.69f, 1.00f },
    [ThemeEmmaColor_Text_Subtle_On_Light] = { 0.48f, 0.48f, 0.48f, 1.00f },
    [ThemeEmmaColor_Icon_Subtle_On_Light] = { 0.69f, 0.69f, 0.69f, 1.00f },
    [ThemeEmmaColor_Icon_Subtle_On_Dark] = { 0.48f, 0.48f, 0.48f, 1.00f },
    [ThemeEmmaColor_Border_Subtle_On_Light] = { 0.69f, 0.69f, 0.69f, 1.00f },
    [ThemeEmmaColor_Border_Subtle_On_Dark] = { 0.48f, 0.48f, 0.48f, 1.00f },
    [ThemeEmmaColor_Background_System_Strong_On_Light] = { 0.69f, 0.69f, 0.69f, 1.00f },
    [ThemeEmmaColor_Background_System_Strong_On_Dark] = { 0.08f, 0.09f, 0.11f, 1.00f },
    [ThemeEmmaColor_Background_System_Hovered_On_Light] = { 0.91f, 0.91f, 0.91f, 1.00f },
    [ThemeEmmaColor_Background_System_Hovered_On_Dark] = { 0.23f, 0.25f, 0.26f, 1.00f },
    [ThemeEmmaColor_Background_Brand_Base] = { 0.07f, 0.58f, 0.95f, 1.00f },
    [ThemeEmmaColor_Background_Brand_Subtle] = { 0.77f, 0.93f, 0.98f, 1.00f },
    [ThemeEmmaColor_Background_Brand_Strong] = { 0.02f, 0.27f, 0.55f, 1.00f },
    [ThemeEmmaColor_Background_Brand_Hovered] = { 0.38f, 0.75f, 0.94f, 1.00f },
    [ThemeEmmaColor_Text_Brand_Base] = { 0.07f, 0.58f, 0.95f, 1.00f },
    [ThemeEmmaColor_Text_Brand_Subtle] = { 0.38f, 0.75f, 0.94f, 1.00f },
    [ThemeEmmaColor_Text_Brand_Strong] = { 0.03f, 0.36f, 0.68f, 1.00f },
    [ThemeEmmaColor_Text_Brand_On_Brand] = { 0.95f, 0.99f, 1.00f, 1.00f },
    [ThemeEmmaColor_Icon_Brand_Base] = { 0.07f, 0.58f, 0.95f, 1.00f },
    [ThemeEmmaColor_Icon_Brand_Subtle] = { 0.38f, 0.75f, 0.94f, 1.00f },
    [ThemeEmmaColor_Icon_Brand_Strong] = { 0.03f, 0.36f, 0.68f, 1.00f },
    [ThemeEmmaColor_Icon_Brand_On_Brand] = { 0.95f, 0.99f, 1.00f, 1.00f },
    [ThemeEmmaColor_Border_Brand_Subtle] = { 0.61f, 0.85f, 0.96f, 1.00f },
    [ThemeEmmaColor_Border_Brand_Base] = { 0.07f, 0.58f, 0.95f, 1.00f },
    [ThemeEmmaColor_Border_Brand_Strong] = { 0.02f, 0.27f, 0.55f, 1.00f },
    [ThemeEmmaColor_Background_Secondary_Base] = { 0.36f, 0.43f, 0.60f, 1.00f },
    [ThemeEmmaColor_Background_Secondary_Subtle] = { 0.71f, 0.78f, 0.84f, 1.00f },
    [ThemeEmmaColor_Background_Secondary_Strong] = { 0.13f, 0.18f, 0.36f, 1.00f },
    [ThemeEmmaColor_Background_Secondary_Hovered] = { 0.51f, 0.60f, 0.72f, 1.00f },
    [ThemeEmmaColor_Text_Secondary_Base] = { 0.36f, 0.43f, 0.60f, 1.00f },
    [ThemeEmmaColor_Text_Secondary_Subtle] = { 0.51f, 0.60f, 0.72f, 1.00f },
    [ThemeEmmaColor_Text_Secondary_Strong] = { 0.13f, 0.18f, 0.36f, 1.00f },
    [ThemeEmmaColor_Text_Secondary_On_Secondary] = { 0.96f, 0.97f, 0.98f, 1.00f },
    [ThemeEmmaColor_Icon_Secondary_Base] = { 0.36f, 0.43f, 0.60f, 1.00f },
    [ThemeEmmaColor_Icon_Secondary_Subtle] = { 0.51f, 0.60f, 0.72f, 1.00f },
    [ThemeEmmaColor_Icon_Secondary_Strong] = { 0.13f, 0.18f, 0.36f, 1.00f },
    [ThemeEmmaColor_Icon_Secondary_On_Secondary] = { 0.96f, 0.97f, 0.98f, 1.00f },
    [ThemeEmmaColor_Border_Secondary_Subtle] = { 0.71f, 0.78f, 0.84f, 1.00f },
    [ThemeEmmaColor_Border_Secondary_Base] = { 0.36f, 0.43f, 0.60f, 1.00f },
    [ThemeEmmaColor_Border_Secondary_Strong] = { 0.13f, 0.18f, 0.36f, 1.00f },
    [ThemeEmmaColor_Background_Danger_Base] = { 0.74f, 0.06f, 0.06f, 1.00f },
    [ThemeEmmaColor_Background_Danger_Subtle] = { 0.97f, 0.92f, 0.88f, 1.00f },
    [ThemeEmmaColor_Background_Danger_Strong] = { 0.74f, 0.06f, 0.06f, 1.00f },
    [ThemeEmmaColor_Background_Danger_Hovered] = { 0.82f, 0.37f, 0.29f, 1.00f },
    [ThemeEmmaColor_Text_Danger_Base] = { 0.74f, 0.06f, 0.06f, 1.00f },
    [ThemeEmmaColor_Text_Danger_Subtle] = { 0.82f, 0.37f, 0.29f, 1.00f },
    [ThemeEmmaColor_Text_Danger_Strong] = { 0.74f, 0.06f, 0.06f, 1.00f },
    [ThemeEmmaColor_Text_Danger_On_Danger] = { 0.99f, 0.96f, 0.94f, 1.00f },
    [ThemeEmmaColor_Icon_Danger_Base] = { 0.74f, 0.06f, 0.06f, 1.00f },
    [ThemeEmmaColor_Icon_Danger_Subtle] = { 0.82f, 0.37f, 0.29f, 1.00f },
    [ThemeEmmaColor_Icon_Danger_Strong] = { 0.74f, 0.06f, 0.06f, 1.00f },
    [ThemeEmmaColor_Icon_Danger_On_Danger] = { 0.99f, 0.96f, 0.94f, 1.00f },
    [ThemeEmmaColor_Border_Danger_Subtle] = { 0.90f, 0.67f, 0.58f, 1.00f },
    [ThemeEmmaColor_Border_Danger_Base] = { 0.82f, 0.37f, 0.29f, 1.00f },
    [ThemeEmmaColor_Border_Danger_Strong] = { 0.67f, 0.05f, 0.05f, 1.00f },
    [ThemeEmmaColor_Background_Warning_Base] = { 0.95f, 0.74f, 0.32f, 1.00f },
    [ThemeEmmaColor_Background_Warning_Subtle] = { 0.99f, 0.96f, 0.90f, 1.00f },
    [ThemeEmmaColor_Background_Warning_Strong] = { 0.93f, 0.61f, 0.05f, 1.00f },
    [ThemeEmmaColor_Background_Warning_Hovered] = { 0.95f, 0.74f, 0.32f, 1.00f },
    [ThemeEmmaColor_Text_Warning_Base] = { 0.56f, 0.28f, 0.02f, 1.00f },
    [ThemeEmmaColor_Text_Warning_Subtle] = { 0.95f, 0.74f, 0.32f, 1.00f },
    [ThemeEmmaColor_Text_Warning_Strong] = { 0.93f, 0.61f, 0.05f, 1.00f },
    [ThemeEmmaColor_Text_Warning_On_Warning] = { 1.00f, 0.99f, 0.95f, 1.00f },
    [ThemeEmmaColor_Icon_Warning_Base] = { 0.56f, 0.28f, 0.02f, 1.00f },
    [ThemeEmmaColor_Icon_Warning_Subtle] = { 0.95f, 0.74f, 0.32f, 1.00f },
    [ThemeEmmaColor_Icon_Warning_Strong] = { 0.93f, 0.61f, 0.05f, 1.00f },
    [ThemeEmmaColor_Icon_Warning_On_Warning] = { 1.00f, 0.99f, 0.95f, 1.00f },
    [ThemeEmmaColor_Border_Warning_Subtle] = { 0.97f, 0.85f, 0.60f, 1.00f },
    [ThemeEmmaColor_Border_Warning_Base] = { 0.95f, 0.74f, 0.32f, 1.00f },
    [ThemeEmmaColor_Border_Warning_Strong] = { 0.70f, 0.38f, 0.03f, 1.00f },
    [ThemeEmmaColor_Background_Success_Base] = { 0.18f, 0.74f, 0.27f, 1.00f },
    [ThemeEmmaColor_Background_Success_Subtle] = { 0.90f, 0.97f, 0.94f, 1.00f },
    [ThemeEmmaColor_Background_Success_Strong] = { 0.15f, 0.67f, 0.24f, 1.00f },
    [ThemeEmmaColor_Background_Success_Hovered] = { 0.39f, 0.82f, 0.52f, 1.00f },
    [ThemeEmmaColor_Text_Success_Base] = { 0.07f, 0.44f, 0.12f, 1.00f },
    [ThemeEmmaColor_Text_Success_Subtle] = { 0.18f, 0.74f, 0.27f, 1.00f },
    [ThemeEmmaColor_Text_Success_Strong] = { 0.02f, 0.21f, 0.04f, 1.00f },
    [ThemeEmmaColor_Text_Success_On_Success] = { 0.95f, 0.99f, 0.97f, 1.00f },
    [ThemeEmmaColor_Icon_Success_Base] = { 0.07f, 0.44f, 0.12f, 1.00f },
    [ThemeEmmaColor_Icon_Success_Subtle] = { 0.18f, 0.74f, 0.27f, 1.00f },
    [ThemeEmmaColor_Icon_Success_Strong] = { 0.02f, 0.21f, 0.04f, 1.00f },
    [ThemeEmmaColor_Icon_Success_On_Success] = { 0.95f, 0.99f, 0.97f, 1.00f },
    [ThemeEmmaColor_Border_Success_Subtle] = { 0.63f, 0.90f, 0.74f, 1.00f },
    [ThemeEmmaColor_Border_Success_Base] = { 0.39f, 0.82f, 0.52f, 1.00f },
    [ThemeEmmaColor_Border_Success_Strong] = { 0.07f, 0.44f, 0.12f, 1.00f },
    [ThemeEmmaColor_Background_Information_Base] = { 0.47f, 0.63f, 0.82f, 1.00f },
    [ThemeEmmaColor_Background_Information_Subtle] = { 0.89f, 0.95f, 0.98f, 1.00f },
    [ThemeEmmaColor_Background_Information_Strong] = { 0.21f, 0.34f, 0.55f, 1.00f },
    [ThemeEmmaColor_Background_Information_Hovered] = { 0.69f, 0.84f, 0.94f, 1.00f },
    [ThemeEmmaColor_Text_Information_Base] = { 0.21f, 0.34f, 0.55f, 1.00f },
    [ThemeEmmaColor_Text_Information_Subtle] = { 0.69f, 0.84f, 0.94f, 1.00f },
    [ThemeEmmaColor_Text_Information_Strong] = { 0.21f, 0.34f, 0.55f, 1.00f },
    [ThemeEmmaColor_Text_Information_On_Information] = { 0.98f, 1.00f, 1.00f, 1.00f },
    [ThemeEmmaColor_Icon_Information_Base] = { 0.21f, 0.34f, 0.55f, 1.00f },
    [ThemeEmmaColor_Icon_Information_Subtle] = { 0.69f, 0.84f, 0.94f, 1.00f },
    [ThemeEmmaColor_Icon_Information_Strong] = { 0.21f, 0.34f, 0.55f, 1.00f },
    [ThemeEmmaColor_Icon_Information_On_Information] = { 0.98f, 1.00f, 1.00f, 1.00f },
    [ThemeEmmaColor_Border_Information_Subtle] = { 0.82f, 0.91f, 0.96f, 1.00f },
    [ThemeEmmaColor_Border_Information_Base] = { 0.69f, 0.84f, 0.94f, 1.00f },
    [ThemeEmmaColor_Border_Information_Strong] = { 0.32f, 0.47f, 0.68f, 1.00f },
    [ThemeEmmaColor_Background_Disabled_On_Light] = { 0.96f, 0.96f, 0.96f, 1.00f },
    [ThemeEmmaColor_Background_Disabled_On_Dark] = { 0.23f, 0.25f, 0.26f, 1.00f },
    [ThemeEmmaColor_Text_Disabled_On_Light] = { 0.69f, 0.69f, 0.69f, 1.00f },
    [ThemeEmmaColor_Text_Disabled_On_Dark] = { 0.48f, 0.48f, 0.48f, 1.00f },
    [ThemeEmmaColor_Icon_Disabled_On_Light] = { 0.80f, 0.80f, 0.80f, 1.00f },
    [ThemeEmmaColor_Icon_Disabled_On_Dark] = { 0.48f, 0.48f, 0.48f, 1.00f },
    [ThemeEmmaColor_Border_Disabled_On_Light] = { 0.80f, 0.80f, 0.80f, 1.00f },
    [ThemeEmmaColor_Border_Disabled_On_Dark] = { 0.23f, 0.25f, 0.26f, 1.00f },
    [ThemeEmmaColor_Text_On_Dark] = { 0.96f, 0.97f, 0.97f, 1.00f },
    [ThemeEmmaColor_Text_On_Light] = { 0.12f, 0.13f, 0.16f, 1.00f },
    [ThemeEmmaColor_Text_Interactive] = { 0.07f, 0.58f, 0.95f, 1.00f },
    [ThemeEmmaColor_Text_Subtlest_On_Dark] = { 0.28f, 0.29f, 0.30f, 1.00f },
    [ThemeEmmaColor_Text_Subtlest_On_Light] = { 0.69f, 0.69f, 0.69f, 1.00f },
    [ThemeEmmaColor_Icon_Subtlest_On_Light] = { 0.80f, 0.80f, 0.80f, 1.00f },
    [ThemeEmmaColor_Icon_Subtlest_On_Dark] = { 0.23f, 0.25f, 0.26f, 1.00f },
    [ThemeEmmaColor_Border_Subtlest_On_Light] = { 0.80f, 0.80f, 0.80f, 1.00f },
    [ThemeEmmaColor_Border_Subtlest_On_Dark] = { 0.23f, 0.25f, 0.26f, 1.00f },
    [ThemeEmmaColor_Icon_On_Dark] = { 0.96f, 0.97f, 0.97f, 1.00f },
    [ThemeEmmaColor_Icon_On_Light] = { 0.12f, 0.13f, 0.16f, 1.00f },
    [ThemeEmmaColor_Border_On_Dark] = { 0.96f, 0.97f, 0.97f, 1.00f },
    [ThemeEmmaColor_Border_On_Light] = { 0.12f, 0.13f, 0.16f, 1.00f },
};


typedef enum {
    ThemeEmmaFont_Size_Heading_1,
    ThemeEmmaFont_Line_Height_Heading_1,
    ThemeEmmaFont_Size_Heading_2,
    ThemeEmmaFont_Line_Height_Heading_2,
    ThemeEmmaFont_Letter_Spacing_Heading_3,
    ThemeEmmaFont_Size_Heading_3,
    ThemeEmmaFont_Letter_Spacing_Heading_4,
    ThemeEmmaFont_Size_Heading_4,
    ThemeEmmaFont_Letter_Spacing_Heading_5,
    ThemeEmmaFont_Size_Heading_5,
    ThemeEmmaFont_Letter_Spacing_Heading_6,
    ThemeEmmaFont_Size_Heading_6,
    ThemeEmmaFont_Letter_Spacing_Subtitle_1,
    ThemeEmmaFont_Size_Subtitle_1,
    ThemeEmmaFont_Letter_Spacing_Subtitle_2,
    ThemeEmmaFont_Size_Subtitle_2,
    ThemeEmmaFont_Letter_Spacing_Body_1,
    ThemeEmmaFont_Size_Body_1,
    ThemeEmmaFont_Letter_Spacing_Body_2,
    ThemeEmmaFont_Size_Body_2,
    ThemeEmmaFont_Letter_Spacing_Caption,
    ThemeEmmaFont_Size_Caption,
    ThemeEmmaFont_Letter_Spacing_Footnote,
    ThemeEmmaFont_Size_Foonote,
    ThemeEmmaFont_Letter_Spacing_Overline,
    ThemeEmmaFont_Size_Overline,
    ThemeEmmaFont_Letter_Spacing_Label,
    ThemeEmmaFont_Size_Label_Large,
    ThemeEmmaFont_Size_Label_Medium,
    ThemeEmmaFont_Size_Label_Small,
    ThemeEmmaSize_Margin_Tablet,
    ThemeEmmaSize_Width_Desktop_Full,
    ThemeEmmaSize_Width_Desktop_Container,
    ThemeEmmaSize_Width_Tablet_Full,
    ThemeEmmaSize_Width_Tablet_Container,
    ThemeEmmaSize_Width_Mobile_Full,
    ThemeEmmaSize_Width_Input_Large,
    ThemeEmmaSize_Width_Border_Base,
    ThemeEmmaSize_Width_Border_Large,
    ThemeEmmaSize_Width_Border_Stats_Small,
    ThemeEmmaSize_Width_Border_Stats_Medium,
    ThemeEmmaSize_Width_Border_Stats_Large,
    ThemeEmmaSize_Width_Border_Stats_Extra_Large,
    ThemeEmmaSize_Width_Input_Medium,
    ThemeEmmaSize_Width_Input_Small,
    ThemeEmmaSize_Width_Mobile_Container,
    ThemeEmmaSize_Width_Email,
    ThemeEmmaSize_Icon_Medium,
    ThemeEmmaSize_Height_Input_Large,
    ThemeEmmaSize_Height_Input_Medium,
    ThemeEmmaSize_Height_Input_Small,
    ThemeEmmaSize_Height_Tag,
    ThemeEmmaSize_Icon_Extra_Small,
    ThemeEmmaSize_Icon_Small,
    ThemeEmmaSize_Margin_Mobile,
    ThemeEmmaSize_Margin_Desktop,
    ThemeEmmaSize_Icon_Large,
    ThemeEmmaSize_Space_Extra_Small,
    ThemeEmmaSize_Radius_Small,
    ThemeEmmaSize_Radius_Base,
    ThemeEmmaSize_Radius_Large,
    ThemeEmmaSize_Radius_Pill,
    ThemeEmmaSize_Space_Small,
    ThemeEmmaSize_Space_Medium,
    ThemeEmmaSize_Space_Large,
    ThemeEmmaSize_Space_Extra_Large,
    ThemeEmmaSize_Space_Extra_Large_2,
    ThemeEmmaSize_Space_Extra_Large_3,
    ThemeEmmaSize_Space_Extra_Large_4,
    ThemeEmmaSize_Space_Extra_Large_5,
    ThemeEmmaSize_Space_Extra_Large_6,
    ThemeEmmaSize_Space_Extra_Large_7,
    ThemeEmmaSize_Radius_Button,
    ThemeEmmaSize_Radius_Input,
    ThemeEmmaSize_Radius_Surface,
    ThemeEmmaSize_COUNT,
} ThemeEmmaSize;

static const float THEME_EMMA_SIZE[] ={
    [ThemeEmmaFont_Size_Heading_1] = 96.0f,
    [ThemeEmmaFont_Line_Height_Heading_1] = 90.0f,
    [ThemeEmmaFont_Size_Heading_2] = 60.0f,
    [ThemeEmmaFont_Line_Height_Heading_2] = 66.0f,
    [ThemeEmmaFont_Letter_Spacing_Heading_3] = 0.0f,
    [ThemeEmmaFont_Size_Heading_3] = 48.0f,
    [ThemeEmmaFont_Letter_Spacing_Heading_4] = 0.25f,
    [ThemeEmmaFont_Size_Heading_4] = 34.0f,
    [ThemeEmmaFont_Letter_Spacing_Heading_5] = 0.0f,
    [ThemeEmmaFont_Size_Heading_5] = 24.0f,
    [ThemeEmmaFont_Letter_Spacing_Heading_6] = 0.15f,
    [ThemeEmmaFont_Size_Heading_6] = 20.0f,
    [ThemeEmmaFont_Letter_Spacing_Subtitle_1] = 0.15f,
    [ThemeEmmaFont_Size_Subtitle_1] = 16.0f,
    [ThemeEmmaFont_Letter_Spacing_Subtitle_2] = 0.1f,
    [ThemeEmmaFont_Size_Subtitle_2] = 14.0f,
    [ThemeEmmaFont_Letter_Spacing_Body_1] = 0.5f,
    [ThemeEmmaFont_Size_Body_1] = 16.0f,
    [ThemeEmmaFont_Letter_Spacing_Body_2] = 0.25f,
    [ThemeEmmaFont_Size_Body_2] = 14.0f,
    [ThemeEmmaFont_Letter_Spacing_Caption] = 0.55f,
    [ThemeEmmaFont_Size_Caption] = 12.0f,
    [ThemeEmmaFont_Letter_Spacing_Footnote] = 0.4f,
    [ThemeEmmaFont_Size_Foonote] = 11.0f,
    [ThemeEmmaFont_Letter_Spacing_Overline] = 1.5f,
    [ThemeEmmaFont_Size_Overline] = 12.0f,
    [ThemeEmmaFont_Letter_Spacing_Label] = 1.25f,
    [ThemeEmmaFont_Size_Label_Large] = 16.0f,
    [ThemeEmmaFont_Size_Label_Medium] = 14.0f,
    [ThemeEmmaFont_Size_Label_Small] = 11.0f,
    [ThemeEmmaSize_Margin_Tablet] = 52.0f,
    [ThemeEmmaSize_Width_Desktop_Full] = 1440.0f,
    [ThemeEmmaSize_Width_Desktop_Container] = 1348.0f,
    [ThemeEmmaSize_Width_Tablet_Full] = 768.0f,
    [ThemeEmmaSize_Width_Tablet_Container] = 664.0f,
    [ThemeEmmaSize_Width_Mobile_Full] = 360.0f,
    [ThemeEmmaSize_Width_Input_Large] = 124.0f,
    [ThemeEmmaSize_Width_Border_Base] = 1.0f,
    [ThemeEmmaSize_Width_Border_Large] = 3.0f,
    [ThemeEmmaSize_Width_Border_Stats_Small] = 16.0f,
    [ThemeEmmaSize_Width_Border_Stats_Medium] = 24.0f,
    [ThemeEmmaSize_Width_Border_Stats_Large] = 32.0f,
    [ThemeEmmaSize_Width_Border_Stats_Extra_Large] = 46.0f,
    [ThemeEmmaSize_Width_Input_Medium] = 110.0f,
    [ThemeEmmaSize_Width_Input_Small] = 80.0f,
    [ThemeEmmaSize_Width_Mobile_Container] = 320.0f,
    [ThemeEmmaSize_Width_Email] = 720.0f,
    [ThemeEmmaSize_Icon_Medium] = 24.0f,
    [ThemeEmmaSize_Height_Input_Large] = 52.0f,
    [ThemeEmmaSize_Height_Input_Medium] = 46.0f,
    [ThemeEmmaSize_Height_Input_Small] = 32.0f,
    [ThemeEmmaSize_Height_Tag] = 24.0f,
    [ThemeEmmaSize_Icon_Extra_Small] = 8.0f,
    [ThemeEmmaSize_Icon_Small] = 16.0f,
    [ThemeEmmaSize_Margin_Mobile] = 20.0f,
    [ThemeEmmaSize_Margin_Desktop] = 46.0f,
    [ThemeEmmaSize_Icon_Large] = 46.0f,
    [ThemeEmmaSize_Space_Extra_Small] = 2.0f,
    [ThemeEmmaSize_Radius_Small] = 4.0f,
    [ThemeEmmaSize_Radius_Base] = 8.0f,
    [ThemeEmmaSize_Radius_Large] = 12.0f,
    [ThemeEmmaSize_Radius_Pill] = 9999.0f,
    [ThemeEmmaSize_Space_Small] = 4.0f,
    [ThemeEmmaSize_Space_Medium] = 8.0f,
    [ThemeEmmaSize_Space_Large] = 12.0f,
    [ThemeEmmaSize_Space_Extra_Large] = 16.0f,
    [ThemeEmmaSize_Space_Extra_Large_2] = 20.0f,
    [ThemeEmmaSize_Space_Extra_Large_3] = 32.0f,
    [ThemeEmmaSize_Space_Extra_Large_4] = 46.0f,
    [ThemeEmmaSize_Space_Extra_Large_5] = 64.0f,
    [ThemeEmmaSize_Space_Extra_Large_6] = 96.0f,
    [ThemeEmmaSize_Space_Extra_Large_7] = 128.0f,
    [ThemeEmmaSize_Radius_Button] = 8.0f,
    [ThemeEmmaSize_Radius_Input] = 8.0f,
    [ThemeEmmaSize_Radius_Surface] = 8.0f,
};
#endif
